name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

    - run: npm test

    # Docker steps to build and push to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/my-node-app:${{ github.sha }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push your-dockerhub-username/my-node-app:${{ github.sha }}

    # Optional: Tag the image with the "latest" tag
    - name: Tag and Push Latest Docker Image
      run: |
        docker tag your-dockerhub-username/my-node-app:${{ github.sha }} your-dockerhub-username/my-node-app:latest
        docker push your-dockerhub-username/my-node-app:latest

